const IMG='https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/';
function photos(e){
  if(!e[5]) return '<div class="artplaceholder"><div>TECNICA</div><small>'+e[9]+'</small></div>';
  const frames=e[6]==='single'?[1]:[0,1];
  return '<div class="artpair '+(frames.length===1?'single':'')+'">'+frames.map((n,i)=>'<figure class="frame"><img src="'+IMG+e[5]+'/'+n+'.jpg" alt="'+e[0]+' · '+(frames.length===1?'posizione':i===0?'inizio':'fine')+'" loading="lazy" decoding="async"><figcaption>'+(frames.length===1?'POSIZIONE':i===0?'INIZIO':'FINE')+'</figcaption></figure>').join('')+'</div>';
}
function sessionNote(w){
  const sets=w[3].reduce((sum,e)=>sum+parseInt(e[2]),0);
  return w[3].length+' esercizi · '+sets+' serie. Riserva 8–10 min al riscaldamento e 8–12 min ai cambi attrezzo. Recuperi dopo ogni serie; negli esercizi per lato completa entrambi prima del recupero. Mantieni circa 2 ripetizioni di margine. '+(w[0]<'D'?'Se arrivi a 60 min, riduci di una serie gli ultimi complementari per concludere entro 70 min.':'Non serve riempire tutti i 90 min: termina quando hai completato il lavoro previsto.');
}
function render(){let h='';W.forEach(w=>{h+=`<section class="workout ${w[2]}" id="w-${w[0]}"><div class="head"><div><small>ALLENAMENTO ${w[0]}</small><h2>${w[1]}</h2><p class="duration">${w[0] < 'D' ? 'Obiettivo 65–70 min' : 'Fino a 90 min'}</p></div><button data-reset="${w[0]}">Azzera</button></div><div class="time-tip">${sessionNote(w)}</div><div class="list">`;let last='';w[3].forEach((e,i)=>{if(e[7]!==last){last=e[7];h+=`<div class="group-label">${last}</div>`}const k=e[8];h+=`<article class="exercise" data-workout="${w[0]}">${photos(e)}<div class="body"><div class="top"><span class="num">${i+1}</span><div><h3>${e[0]}</h3><div class="meta">🧰 ${e[1]}<br>🔁 ${e[2]} · ⏱ ${e[3]}</div></div><label class="done"><input type="checkbox" data-key="${k}-done">✓</label></div><div class="track"><label>Peso<input inputmode="decimal" placeholder="kg" data-key="${k}-peso"></label><label>Rip. fatte<input inputmode="numeric" placeholder="es. 12" data-key="${k}-reps"></label></div><a class="video" href="${e[4]}" target="_blank" rel="noopener">${e[4].includes('/results?') ? '▶ Cerca video della variante' : '▶ Apri guida e video'}</a>${e[5] ? `<p class="cue">${e[9]}</p>` : ''}<details><summary>Note personali</summary><textarea rows="2" data-key="${k}-note" placeholder="Tecnica, carico, sensazioni…"></textarea></details></div></article>`});h+='</div></section>'});document.getElementById('app').innerHTML=h;bind()}
function bind(){const els=[...document.querySelectorAll('[data-key]')];els.forEach(el=>{const k='pale-'+el.dataset.key,v=localStorage.getItem(k);if(v!==null)el.type==='checkbox'?el.checked=v==='1':el.value=v;el.addEventListener(el.type==='checkbox'?'change':'input',()=>{localStorage.setItem(k,el.type==='checkbox'?(el.checked?'1':'0'):el.value);progress()})});document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-workout="'+b.dataset.reset+'"] [data-key]').forEach(el=>{localStorage.removeItem('pale-'+el.dataset.key);el.type==='checkbox'?el.checked=false:el.value=''});progress()});progress()}
function progress(){const b=[...document.querySelectorAll('input[type=checkbox][data-key]')],d=b.filter(x=>x.checked).length,p=b.length?Math.round(d*100/b.length):0;document.getElementById('fill').style.width=p+'%';document.getElementById('prog').textContent=p+'% completato · '+d+'/'+b.length+' esercizi'}
render();
document.querySelectorAll('.artpair img').forEach(img=>img.addEventListener('error',()=>{
  const pair=img.closest('.artpair');if(!pair)return;
  const fallback=document.createElement('div');fallback.className='artplaceholder';fallback.textContent='Immagine non disponibile · leggi la tecnica qui sotto';pair.replaceWith(fallback);
}));